{% set name = "pywgrib2_xr" %}
# {% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# {% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set version = "0.2.2" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  # Uncomment the following line if the package is pure Python and the recipe
  # is exactly the same for all platforms. It is okay if the dependencies are
  # not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python
  # for more details.
  # noarch: python

  skip: true    # [win or osx]
  number: {{ build_number }}
  # string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required
    # compilers as separate entries here. Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - cython
    - numpy >=1.17
    - libwgrib2
    - setuptools <50.0
  run:
    - python
    - libwgrib2 >=3.0
    - xarray >=0.16
    - dask >=2.11
    - python-blosc >=1.9
    - wurlitzer >=2
    - mypy_extensions   # [py==37]
  entry_points:
    pywgrib2 = pywgrib2_xr.script:main

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - pywgrib2_xr
  # Run your test commands here
  commands:
    - pywgrib2 -h
    - pytest
  # declare any test-only requirements here
  requires:
    - pytest
    - dill
    - netcdf4
    - zarr
  # copy over any needed test files here
  source_files:
    - tests/
    - data/

# Uncomment and fill in pywgrib2_xr metadata
about:
  home: https://github.com/yt87/pywgrib2_xr
  license: BSD-0-Clause
  license_family: BSD
  license_file: LICENCE
  summary: wgrib2 Python API

# Uncomment the following if this will be on a forge
# Remove these lines if this is only be used for CI
extra:
  recipe-maintainers:
    - yt87
